"""Reproducibility documentation for reviewer packages."""

from __future__ import annotations

from typing import Any

from tdf_product_artifact_builder.version import __version__


def build_reproducibility_md(spec: dict[str, Any]) -> str:
    """Build deterministic REPRODUCIBILITY.md content."""
    product_id = str(spec.get("product_id", ""))
    lines = [
        "# Reproducibility",
        "",
        "This reviewer package is generated by the generic product artifact builder.",
        "Build trust in the artifact, not belief in the theory.",
        "",
        "## Builder",
        "",
        f"- Builder version: `{__version__}`",
        f"- Product ID: `{product_id}`",
        "- Generation method: generic reviewer package builder",
        "- Deterministic output: same product spec yields the same package content",
        "",
        "## Regeneration command",
        "",
        "```bash",
        "python3 tools/build_reviewer_package.py \\",
        "  --product-spec <path-to-product_spec.yaml> \\",
        "  --output-dir <output-directory>",
        "```",
        "",
        "## Scope limits",
        "",
        "- No simulation execution (OpenMM, LAMMPS, or other MD engines).",
        "- No wet-lab validation or fabrication claims.",
        "- No readiness stage upgrade beyond the product spec.",
        "- No upstream TDF repository calls during package generation.",
        "",
    ]
    return "\n".join(lines)
